WHEEL_UP   add volume   2
WHEEL_DOWN add volume  -2
RIGHT      seek   2 exact
LEFT       seek  -2 exact
UP         seek   5 exact
DOWN       seek  -5 exact
Ctrl+RIGHT seek  20 exact
Ctrl+LEFT  seek -20 exact

CTRL+1 add sub-scale +0.1
CTRL+2 add sub-scale -0.1

+ add volume 2
~ add volume -2

CTRL+3 script-binding stats/display-stats-toggle

