###General###
profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
hwdec=nvdec-copy

###Audio###
audio-file-auto=fuzzy

###Subs###
demuxer-mkv-subtitle-preroll=yes
blend-subtitles=yes
sub-fix-timing=no
sub-border-color="#000000"
save-position-on-quit=yes
sub-font="Hiragino Sans"
sub-auto=fuzzy
sub-color="#a9a9a9"
sub-visibility=yes
sub-border-size=3
sub-font-size=35
sub-bold=no
sub-pos=97
sub-shadow-offset=0

###Priority###
alang=jpn, jp
slang=jpn, jp
osc=no

###Deband###
deband=yes

###Dither###
dither-depth = 8

###Static Grain###
scale=ewa_lanczos
scale-blur=0.981251
dscale=ewa_lanczos
cscale=ewa_lanczos

script-opts-append=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=sub-format=ja,sub-lang=ja,sleep-interval=4,write-auto-sub=

# mpv_websocket
# https://github.com/kuroahna/mpv_websocket

# Setting input-ipc-server=/tmp/mpv-socket will work on both Windows and Linux
#
# On Windows, the socket will be available at \\.\pipe\tmp\mpv-socket
# On Linux, the socket will be available at /tmp/mpv-socket
#
# See: https://mpv.io/manual/stable/#options-input-ipc-server
input-ipc-server=/tmp/mpv-socket
