source = ~/.config/hypr/colors.conf


background {
    monitor =
    color = $background          
    path = ~/Pictures/Wallpaper/.current-blurred.jpg
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

general {
    grace = 300
    hide_cursor = false
    no_fade_in = false
}

animations {
    enabled = yes
    animation = glow, 1, 2, default
    animation = fade, 1, 5, default
}

image {
    monitor =
    path = ~/Pictures/discord/30662-pfp.jpeg 
    size = 180
    position = 0, 50
    halign = center
    valign = center
    
    rounding = -1
    shadow_passes = 3
    shadow_size = 15
    shadow_color = $accent
    shadow_boost = 1.2
    border_color = $accent
    border_size = 4
}

label {
    monitor =
    text = おかえりなさい
    color = $primary
    font_size = 20
    font_family = Hiragino Sans
    shadow_color = $primary
    position = 0, -100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 350, 50
    position = 0, -160
    halign = center
    valign = center

    inner_color = $primary
    outer_color = $primary
    outline_thickness = 3
    rounding = 0

    font_color = #000000
    font_family = Hiragino Sans
    font_size = 16

    hide_input = false
    check_color = #000000
    fail_color = #000000              
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    fade_on_empty = true
    fade_timeout = 1000

    dots_center = true
    dots_spacing = 0.3
    dots_radius = 3
}

label {
    monitor =
    text = cmd[update:1000] LANG=ja_JP.UTF-8 date +"%H:%M"
    color = $primary
    font_size = 12
    font_family = Hiragino Sans
    position = 50, 100
    shadow_passes = 3
    shadow_size = 6
    shadow_color = rgba(00000040)
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:43200000] LANG=ja_JP.UTF-8 date +"%Y年%m月%d日 (%a)"
    color = $primary
    font_size = 12
    font_family = Hiragino Sans
    position = 50, 60
    shadow_passes = 2
    shadow_size = 3
    shadow_color = $shadow_color
    halign = left
    valign = bottom
}


label {
    monitor =
    text = cmd[update:2000] ~/.config/hypr/scripts/music.sh --title
    color = $primary
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono
    position = -130, 85
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:2000] ~/.config/hypr/scripts/music.sh --artist
    color = $primary              
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono
    position = -130, 65
    halign = right
    valign = bottom
}


label {
    monitor =
    text =  再起動 
    color = $primary
    font_size = 12
    onclick = reboot
    position = 120, 75
    halign = center
    valign = bottom
}

label {
    monitor =
    text =  電源オフ 
    color = $primary
    font_size = 12
    onclick = shutdown now
    position = 0, 75
    halign = center
    valign = bottom
}

label {
    monitor =
    text =  サスペンド 
    color = $primary
    font_size = 12
    onclick = systemctl suspend
    position = -120, 75
    halign = center
    valign = bottom
}

auth {
    fingerprint:enabled = true
    fingerprint:type = auto
}
